import type { Metadata } from "next";
// import ApolloWrapper from "../apolo/ApolloWrapper";
// import Navbar from "@/components/Navbar/Navbar";
import Navbar from "@/components/Navbar/Navbar";
import { StateProvider } from "@/components/StateProvider";
import "./global.scss";

export const metadata: Metadata = {
  title: "Ulon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StateProvider>
          {/*<ApolloWrapper>*/}
          <Navbar />
          {children}
          {/*</ApolloWrapper>*/}
        </StateProvider>
      </body>
    </html>
  );
}
