import ClientLayout from "./ClientLayout";
import "./global.scss";
import "./globals.css";
import "@/scss/custom/input.scss";
import "@/scss/custom/textarea.scss";
import "@/scss/custom/search.scss";
import "@/scss/custom/checkbox.scss";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
  title: "Ulon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}', {
              page_path: window.location.pathname,
            });
          `}
        </Script>
      </head>
      <body>
   
        <ClientLayout>{children} </ClientLayout>
        <Analytics />
      </body>
    </html>
  );
}
