import type {Metadata} from "next";
// import ApolloWrapper from "../apolo/ApolloWrapper";
// import Navbar from "@/components/Navbar/Navbar";
import Navigation from "@/components/Navigation/Navigation";
import {StateProvider} from "@/components/StateProvider";
import "./global.scss";


export const metadata: Metadata = {
    title: "Ulon",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <StateProvider>
            {/*<ApolloWrapper>*/}
            <Navigation/>
            {children}
            {/*</ApolloWrapper>*/}
        </StateProvider>
        </body>
        </html>
    );
}
