// pubsub.js
import { PubSub } from "graphql-subscriptions";

const pubsub = new PubSub();

const USER_CREATED = "USER_CREATED";
const USER_DELETED = "USER_DELETED";
const USER_LOGGEDIN = "USER_LOGGEDIN";
const USER_LOGGEDOUT = "USER_LOGGEDOUT";
const CHAT_CREATED = "CHAT_CREATED";
const CHAT_DELETED = "CHAT_DELETED";
const MESSAGE_SENT = "MESSAGE_SENT";
const MESSAGE_DELETED = "MESSAGE_DELETED";


const POST_DELETED = "POST_DELETED";
const POST_LIKED = "POST_LIKED";
const POST_DISLIKED = "POST_DISLIKED";
const POST_CREATED = "POST_CREATED";

const COMMENT_ADDED = "COMMENT_ADDED";
const COMMENT_DELETED = "COMMENT_DELETED";


// const REACTION_CHANGED = "REACTION_CHANGED";
// const COMMENT_CREATED = "COMMENT_CREATED";
// const POST_DELETED = "POST_DELETED";
// const POST_COMMENT_DELETED = "POST_COMMENT_DELETED";
// const COMMENT_REACTION_CHANGED = "COMMENT_REACTION_CHANGED";
export {
  pubsub,
  USER_CREATED,
  USER_DELETED,
  USER_LOGGEDIN,
  USER_LOGGEDOUT,
  CHAT_CREATED,
  CHAT_DELETED,
  MESSAGE_SENT,
  MESSAGE_DELETED,
  POST_DELETED,
 
  POST_LIKED,
  POST_DISLIKED,
  POST_CREATED,

  COMMENT_ADDED,
  COMMENT_DELETED
};
