// pubsub.js
import { PubSub } from "graphql-subscriptions";

const pubsub = new PubSub();

const USER_CREATED = "USER_CREATED";
const USER_DELETED = "USER_DELETED";
const USER_LOGGEDIN = "USER_LOGGEDIN";
const USER_LOGGEDOUT = "USER_LOGGEDOUT";
const CHAT_CREATED = "CHAT_CREATED";
const CHAT_DELETED = "CHAT_DELETED";
const MESSAGE_SENT = "MESSAGE_SENT";
const POST_CREATED = "POST_CREATED";
const REACTION_CHANGED = "REACTION_CHANGED";
const COMMENT_CREATED = "COMMENT_CREATED";
const POST_DELETED = "POST_DELETED";
const POST_COMMENT_DELETED = "POST_COMMENT_DELETED";
const COMMENT_REACTION_CHANGED = "COMMENT_REACTION_CHANGED";
export {
  pubsub,
  USER_CREATED,
  USER_DELETED,
  USER_LOGGEDIN,
  USER_LOGGEDOUT,
  CHAT_CREATED,
  CHAT_DELETED,
  MESSAGE_SENT,
  POST_CREATED,
  REACTION_CHANGED,
  COMMENT_CREATED,
  POST_DELETED,
  POST_COMMENT_DELETED,
  COMMENT_REACTION_CHANGED,
};
